// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wltvwgegxvmapucnzmax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsdHZ3Z2VneHZtYXB1Y256bWF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2MDk2NTksImV4cCI6MjA1NTE4NTY1OX0.M1bEpVcwjYsUBkht4OxuNr9xCbFS6t1rOgRHhEdgBuA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);